apiVersion: v1
description: High Performance, Kubernetes Native Object Storage
name: minio
version: 1.1.0
appVersion: master
keywords:
- storage
- object-storage
- S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
- https://github.com/minio/charts
upstream_version: 8.0.5
dependencies:
  - name: common
    repository: file://../../../library/common/2101.0.0
    version: 2101.0.0
