## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: ghcr.io/tron-us/go-btfs
  tag: v1.5.1-release
  pullPolicy: IfNotPresent

## Additional arguments to pass to ipfs binary
extraArgs: []

updateStrategy: Recreate

service:
  swarmPort: 9401
  apiPort: 9501
  gatewayPort: 9880

environment:

appVolumeMounts:
  staging:
    emptyDir: true
    mountPath: "/export"
  data:
    emptyDir: true
    mountPath: "/data/btfs"

