## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: ghcr.io/tron-us/go-btfs
  tag: v1.5.1-release
  pullPolicy: IfNotPresent

## Additional arguments to pass to minio binary
extraArgs: []

updateStrategy: Recreate

service:
  swarmPort: 30941
  apiPort: 30951
  gatewayPort: 30980

environmentVariables: []

emptyDirVolumes: true
appVolumeMounts:
  staging:
    emptyDir: true
    mountPath: "/export"
  data:
    emptyDir: true
    mountPath: "/data/btfs"
