## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: ixsystems/btfs-truenas-docker
  tag: v1.5.0
  pullPolicy: IfNotPresent

## Additional arguments to pass to ipfs binary
extraArgs: []

updateStrategy: Recreate

service:
  swarmPort: 9401
  apiPort: 9501
  gatewayPort: 9080

environment:

appVolumeMounts:
  staging:
    emptyDir: true
    mountPath: "/export"
  data:
    emptyDir: true
    mountPath: "/data/btfs"

