## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: ipfs/go-ipfs
  tag: v0.8.0-rc1
  pullPolicy: IfNotPresent

## Additional arguments to pass to minio binary
extraArgs: []

updateStrategy: Recreate

service:
  swarmPort: 30941
  apiPort: 30951
  gatewayPort: 30980

environment:

emptyDirVolumes: true

ipfsDataHostPathEnabled: false
ipfsStagingHostPathEnabled: false
